# Site settings
title: oddEvan.com
tagline:  Slightly uneven since 2005.
email: me@eph.me
description: > # this means to ignore newlines until "baseurl:"
  Big-picture analysis and ramblings on
  technology, media, life, the universe, and everything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.oddevan.com" # the base hostname & protocol for your site
twitter_username: oddevan
github_username:  oddevan
permalink:  /:year/:title.html
timezone: America/New_York

# Build settings
markdown: kramdown
